### ISSUE TITLE
SpiritParser not properly implemented yet

### ISSUE THREAD

**Issue by PhilippRue** [JuDFTteam/aiida-spirit#4]
The SpiritCalculation always terminates with exit code 100 (ERROR_MISSING_OUTPUT_FILES) because the [SpiritParser](https://github.com/JuDFTteam/aiida-spirit/blob/a928f18646f5c0149ed606285ff79464f3de0ac1/aiida_spirit/parsers.py#L16) is not properly implemented yet.

- The comparison to the expected list of files in https://github.com/JuDFTteam/aiida-spirit/blob/a928f18646f5c0149ed606285ff79464f3de0ac1/aiida_spirit/parsers.py#L45 does not work properly
- no parsing is done but the [template code from the cookiecutter is still present](https://github.com/JuDFTteam/aiida-spirit/blob/a928f18646f5c0149ed606285ff79464f3de0ac1/aiida_spirit/parsers.py#L53)

**Comment by PhilippRue** [comment]
We should define which information should be parsed from the output files of spirit.

**Comment by PhilippRue** [comment]
Ideas for things that can be parses / should appear in the database:

- [x] initial spin configuration
- [x] final spin configuration
- statistics of the spirit run
  - [ ] total number of iterations
  - [ ] convergence information

**Comment by MSallermann** [comment]
I think the relevant outputs depend strongly on the method that is being run. So far I agree with Philips list and I think these should be the first things to be implemented. For most methods, the energy of the initial/final/ground state would also be interesting.

>       * [ ]  total number of iterations
>       * [ ]  convergence information

_Just as a heads up:_ It is currently not so straight forward to get these from the spirit python API. This is because the functions that query the simulation state (like e.g. `spirit.simulation.get_max_torque_norm`) need to be called from a separate thread, **while the simulation is running.** I will implement a better method on a branch soon.

Other useful outputs might be:
For LLG (Dynamics) (meaning LLG with any solver that is not `VP/LBFGS `  and  `direct_minimization=false`)
- [ ] Snapshots of the spin configuration at different time intervals
- [ ] Energies at different time intervals

For LLG (Minimization) (So we probably expect some metastable configurations)
- [ ] The profile/radius (thinking of Skyrmions)
- [ ] Topological charge

For GNEB
- [ ] The saddle point configuration/energies
- [ ] Energy barrier

For HTST
- [ ] All of the quantities in htst_info
- [ ] Eigenvalues/Eigenvectors (if non sparse calculation)

MC
- [ ] Critical temperatures (requires post processing, so maybe a bit out of scope)
- [ ] Ground state spin configuration (simulated annealing + final minimization with LLG) (How to control convergence?)

**Comment by PhilippRue** [comment]
> _Just as a heads up:_ It is currently not so straight forward to get these from the spirit python API. This is because the functions that query the simulation state (like e.g. `spirit.simulation.get_max_torque_norm`) need to be called from a separate thread, **while the simulation is running.** I will implement a better method on a branch soon.

As long as we can write it to a file or the stdout we are good. The parsing will be done after the spirit calculation has finished and there we extract data from the output files. Therefore we can also look for keywords in the stdout that spirit produces and take the information (e.g. number of iterations) from there.

**Comment by PhilippRue** [comment]
Since the basic parser works I move this to the new issue #8
